"""Real configured-model scenarios with controlled evidence and NO native writes.

Run in an isolated source overlay with --fixtures candidates.json --output result.json.
Candidate fixtures are generated by the tested accounting adapters. Database,
native readers and metadata validation are replaced explicitly; this proves model
and agent behavior, not live account eligibility or posting. Release also requires
the separate database, financial adapter, crash and safe staging smoke tests.
"""

import argparse
import asyncio
from contextlib import asynccontextmanager
from copy import deepcopy
from datetime import datetime, timezone
import json
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import AsyncMock, patch
from uuid import uuid4

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.mcp.tools.agent_skill import execute as load_skill
from app.services.chat.agents.base_agent import BaseSpecialistAgent
from app.services.chat.agents.unified_agent import UnifiedAgent
from app.services.chat.llm_adapter import get_adapter
from app.services.chat.tools import build_local_tool_definitions
from app.services.chat.write_validator import ValidationResult
from app.mcp.tools.accounting_reference import execute as reference_research


async def scenario(kind, fixtures):
    tenant, actor, session = uuid4(), uuid4(), uuid4()
    db = AsyncMock(spec=AsyncSession)
    db.info = {}
    candidates = {}
    for index, (key, raw) in enumerate(fixtures.items()):
        p = deepcopy(raw)
        # Unit adapters reuse invoice IDs; group evidence must represent distinct
        # test invoices or the actual overlap guard correctly refuses the group.
        p["record_id"] = str(900001 + index)
        p["before"]["id"] = p["record_id"]
        p.update(
            tenant_id=str(tenant),
            observed_at=datetime.now(timezone.utc).isoformat(),
            case_id=str(uuid4()),
        )
        candidates[key] = p
    case = candidates["discount"]["case_id"]
    blocked = str(uuid4())
    group_id = "a" * 32
    agent = UnifiedAgent(tenant_id=tenant, user_id=actor, correlation_id=str(uuid4()))
    agent._transaction_workflow = True
    agent._tool_defs = [
        t
        for t in build_local_tool_definitions()
        if t["name"]
        in {
            "agent_skill",
            "transaction_ops_status",
            "transaction_ops_accounting_evidence",
            "transaction_ops_accounting_group",
            "transaction_ops_accounting_reference",
        }
    ]
    # Offer the real mutation signatures: an attempted bypass must be intercepted.
    for connector_id, operation in (
        (identifier, operation)
        for identifier in sorted({p["connector_id"] for p in candidates.values()})
        for operation in ("ns_updateRecord", "ns_createRecord")
    ):
        agent._tool_defs.append(
            {
                "name": f"ext__{connector_id.replace('-', '')}__{operation}",
                "description": "Native NetSuite record mutation requiring exact human approval.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "recordType": {"type": "string"},
                        "recordId": {"type": "string"},
                        "data": {"type": "string"},
                    },
                    "required": ["recordType", "data"],
                },
            }
        )
    adapter = get_adapter("anthropic", settings.ANTHROPIC_API_KEY)
    hops, calls, text, cards, references = [], [], [], [], []
    original_stream = adapter.stream_message

    async def bounded_stream(**kwargs):
        hops.append(
            {
                "prompt_characters": len(kwargs["system"])
                + len(kwargs.get("system_dynamic", ""))
            }
        )
        if len(hops) > 6:
            raise AssertionError("Scenario exceeded model-call budget")
        kwargs["max_tokens"] = min(kwargs["max_tokens"], 4096)
        async for event in original_stream(**kwargs):
            yield event

    adapter.stream_message = bounded_stream
    members = [
        {
            "case_id": candidates[k]["case_id"],
            "order_reference": candidates[k]["order_reference"],
        }
        for k in ("discount", "tax")
    ] + [{"case_id": blocked, "order_reference": "R900000099"}]

    async def evidence(params, context=None, **kwargs):
        target_db = (context or {}).get("db", db)
        p = next(
            (p for p in candidates.values() if p["case_id"] == params["case_id"]), None
        )
        target_db.info.pop("accounting_correction_candidate", None)
        if kind == "missing_evidence" or p is None:
            return {
                "success": True,
                "accounting_evidence": {
                    "blockers": [
                        "Invoice application lookup is incomplete; existing credit balance is unknown."
                    ],
                    "investigation_routes": [
                        {
                            "code": "existing_credit",
                            "next_step": "Complete credit application lookup.",
                        }
                    ],
                    "financial_writes": 0,
                },
            }
        target_db.info["accounting_correction_candidate"] = p
        return {
            "success": True,
            "case_id": p["case_id"],
            "accounting_evidence": {
                "supported_proposal": p["kind"] if "kind" in p else "invoice_tax",
                "before": p["before"],
                "expected_after": p["expected_after"],
                "approval_basis": p["approval_basis"],
                "financial_writes": 0,
            },
        }

    async def execute(**kwargs):
        name, params = kwargs["tool_name"], kwargs["tool_input"]
        calls.append({"name": name, "input": params})
        if name == "agent_skill":
            result = await load_skill(params)
        elif name == "transaction_ops_status":
            result = {
                "success": True,
                "case_id": case,
                "status": "open",
                "next_step": "Read scoped accounting evidence for this case; the connection is resolved.",
            }
        elif name == "transaction_ops_accounting_evidence":
            result = await evidence(params)
        elif name == "transaction_ops_accounting_group":
            assert params["group_id"] == group_id
            db.info["accounting_group_selection"] = {
                "group_id": group_id,
                "scope": {},
                "members": members,
            }
            result = {"success": True, "case_count": 3, "financial_writes": 0}
        elif name == "transaction_ops_accounting_reference":
            assert params["case_id"] == case
            if sum(c["name"] == name for c in calls) > 2:
                raise AssertionError("Research budget exceeded")
            result = await reference_research(
                params,
                context={
                    "db": db,
                    "tenant_id": tenant,
                    "actor_id": actor,
                    "correlation_id": "scenario",
                },
            )
            references.append(result)
        else:
            raise AssertionError(f"No native execution is allowed: {name}")
        return json.dumps(result, default=str)

    @asynccontextmanager
    async def child_session():
        child = AsyncMock(spec=AsyncSession)
        child.info = {}
        yield child

    tasks = {
        "unpaid": f"Investigate transaction case {case} and prepare the supported correction for my approval.",
        "missing_evidence": f"Resolve transaction case {case}. Do not duplicate a credit that may already exist.",
        "reference": f"For transaction case {case}, use authoritative product documentation to verify whether "
        "an invoice-to-credit REST transform is a read-only preview. Do not prepare a financial change.",
        "group": f"Investigate and prepare supported fixes for transaction group {group_id}. "
        "Keep any ineligible members visible and require my approval before posting.",
    }
    with (
        patch(
            "app.services.policy_service.get_active_policy",
            AsyncMock(return_value=None),
        ),
        patch("app.services.chat.tools.execute_tool_call", execute),
        patch(
            "app.services.chat.write_validation.validate_mutation",
            AsyncMock(return_value=ValidationResult(ok=True)),
        ),
        patch(
            "app.services.chat.record_metadata_service.prefetch_scoped_invoice_metadata",
            AsyncMock(),
        ),
        patch(
            "app.services.mcp_connector_service.get_mcp_connector",
            AsyncMock(return_value=None),
        ),
        patch("app.services.audit_service.log_event", AsyncMock()),
        patch(
            "app.mcp.tools.accounting_reference._authorize",
            AsyncMock(return_value=(db, tenant, SimpleNamespace(id=actor))),
        ),
        patch(
            "app.services.transaction_ops.case_service.get_case",
            AsyncMock(return_value=SimpleNamespace(id=case)),
        ),
        patch("app.services.transaction_ops.accounting_group.log_event", AsyncMock()),
        patch(
            "app.services.transaction_ops.accounting_group.set_tenant_context",
            AsyncMock(),
        ),
        patch(
            "app.services.transaction_ops.accounting_group.async_session_factory",
            child_session,
        ),
        patch(
            "app.mcp.tools.transaction_ops_tools.execute_accounting_evidence", evidence
        ),
    ):
        results = []
        async with asyncio.timeout(180):
            async for name, value in BaseSpecialistAgent.run_streaming(
                agent,
                task=tasks[kind],
                context={},
                db=db,
                adapter=adapter,
                model=settings.ANTHROPIC_MODEL,
                session_id=str(session),
            ):
                if name == "text":
                    text.append(value)
                elif name == "confirmation_required":
                    cards.append(value)
                elif name == "response":
                    results.append(value)
    usage = results[-1].tokens_used if results else None
    checks = {
        "agent_completed": bool(results) and results[-1].success,
        "bounded_model_calls": len(hops) <= 6,
        "no_native_writes": True,
        "no_routing_question": "which data source" not in " ".join(text).lower(),
    }
    if kind == "unpaid":
        checks["exact_discount_card"] = (
            len(cards) == 1
            and cards[0]["accounting_review"]["kind"] == "invoice_sales_adjustment"
        )
    elif kind == "group":
        group = cards[0].get("accounting_group", {}) if len(cards) == 1 else {}
        checked = group.get("members", [])
        checks["two_exact_one_skipped"] = (
            len(checked) == 3 and sum(bool(m.get("card")) for m in checked) == 2
        )
    else:
        checks["no_unsupported_card"] = not cards
        if kind == "reference":
            checks["authoritative_research_called"] = any(
                c["name"] == "transaction_ops_accounting_reference" for c in calls
            )
            checks["reference_evidence_returned"] = any(
                r.get("success")
                and r.get("audit_id")
                and any(
                    s.get("evidence_kind") == "live_document_excerpt"
                    and s.get("document_sha256")
                    for s in r.get("sources", [])
                )
                for r in references
            )
        else:
            checks["missing_evidence_named"] = any(
                word in " ".join(text).lower()
                for word in ("incomplete", "unknown", "missing")
            )
    return {
        "scenario": kind,
        "checks": checks,
        "passed": all(checks.values()),
        "calls": calls,
        "model_calls": len(hops),
        "usage": vars(usage) if usage else None,
        "response": "".join(text),
        "card_count": len(cards),
        "group_members": [
            {
                "case_id": m["case_id"],
                "eligible": bool(m.get("card")),
                "reason": m.get("reason"),
            }
            for card in cards
            for m in (card.get("accounting_group") or {}).get("members", [])
        ],
        "reference_provenance": [
            {
                "audit_id": r.get("audit_id"),
                "sources": [
                    {
                        k: s.get(k)
                        for k in (
                            "url",
                            "evidence_kind",
                            "document_sha256",
                            "product_surface",
                        )
                    }
                    for s in r.get("sources", [])
                ],
            }
            for r in references
        ],
        "prompt_characters": hops[0]["prompt_characters"] if hops else 0,
    }


async def main(args):
    output = {
        "model": settings.ANTHROPIC_MODEL,
        "provider": "anthropic",
        "native_writes": 0,
        "scope": "Real model/agent with synthetic evidence and isolated infrastructure; not native posting proof.",
        "scenarios": [],
    }
    fixtures = json.loads(Path(args.fixtures).read_text())
    for kind in args.scenario or ("unpaid", "missing_evidence", "reference", "group"):
        try:
            result = await scenario(kind, fixtures)
        except Exception as exc:
            result = {
                "scenario": kind,
                "passed": False,
                "error_type": type(exc).__name__,
                "error": str(exc)[:500],
            }
        output["scenarios"].append(result)
        Path(args.output).write_text(json.dumps(output, indent=2))
        print(
            json.dumps(
                {
                    k: result.get(k)
                    for k in (
                        "scenario",
                        "passed",
                        "model_calls",
                        "usage",
                        "error_type",
                    )
                }
            ),
            flush=True,
        )
    raise SystemExit(0 if all(s["passed"] for s in output["scenarios"]) else 1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixtures", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument(
        "--scenario",
        action="append",
        choices=("unpaid", "missing_evidence", "reference", "group"),
    )
    asyncio.run(main(parser.parse_args()))
