"""Add tenant learned rules table

Revision ID: 028_tenant_learned_rules
Revises: 027_add_missing_metadata_columns
Create Date: 2026-02-23 18:40:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '028_tenant_learned_rules'
down_revision: Union[str, None] = '027_add_missing_metadata_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_learned_rules',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rule_category', sa.String(length=50), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_learned_rules_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_learned_rules'))
    )
    op.create_index(op.f('ix_tenant_learned_rules_tenant_id'), 'tenant_learned_rules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_learned_rules_tenant_id'), table_name='tenant_learned_rules')
    op.drop_table('tenant_learned_rules')
    # ### end Alembic commands ###
