"""Refresh a fixed review cohort without changing its historical findings."""

from sqlalchemy import DateTime, and_, any_, case, cast, column, func, literal, or_, select, true, tuple_, union_all
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

from app.models.transaction_ops import TransactionRun as Run
from app.services.transaction_ops.source_eligibility import eligible_reports


def evidence_time(report, fallback):
    # Legacy findings must use the same read clock as newly marked findings.
    # Validate before casting: older diagnostic evidence can have absent or
    # malformed snapshots. Match case_service.observation_time's fallback.
    snapshots = func.jsonb_build_array(report["source"]).op("||")(
        case(
            (func.jsonb_typeof(report["targets"]) == "array", report["targets"]),
            else_=literal([], type_=JSONB),
        )
    )
    rows = func.jsonb_array_elements(snapshots).table_valued("value").alias("legacy_snapshot")
    raw = cast(rows.c.value, JSONB)["observed_at"].astext
    parsed = case(
        (
            and_(raw.op("~")(r"(Z|[+-][0-9]{2}:[0-9]{2})$"), func.pg_input_is_valid(raw, "timestamp with time zone")),
            cast(raw, DateTime(timezone=True)),
        )
    )
    legacy = (
        select(
            case(
                (
                    and_(
                        func.jsonb_typeof(report["targets"]) == "array",
                        func.count(parsed) == func.count(),
                        func.max(parsed) <= fallback,
                    ),
                    func.min(parsed),
                ),
                else_=fallback,
            )
        )
        .select_from(rows)
        .correlate_except(rows)
        .scalar_subquery()
    )
    # This marker is generated by record_finding, never accepted from callers.
    return func.coalesce(cast(report["_observation"]["observed_at"].astext, DateTime(timezone=True)), legacy)


def final_evidence(report):
    # Older findings predate the marker. Interim collection remains visible in
    # its run but must not replace a completed case in a period's issue groups.
    return func.coalesce(report["_observation"]["final"].astext, "true") == "true"


def replacement_scope(snapshot):
    """Exact business identity of runs allowed to refresh a review."""
    # A configuration revision may change policy, but a different source,
    # account, entity, identity or currency cannot replace a finding.
    if not (snapshot.get("source_connection_id") or snapshot.get("source_step_id")) or not all(
        snapshot.get(key) for key in ("netsuite_account_id", "subsidiary_id", "record_type")
    ):
        return None
    scope = [
        Run.config_snapshot[key].astext == snapshot.get(key)
        for key in ("source_connection_id", "source_step_id", "subsidiary_id", "record_type")
    ]
    account = str(snapshot["netsuite_account_id"]).replace("_", "-").lower()
    scope.append(func.lower(func.replace(Run.config_snapshot["netsuite_account_id"].astext, "_", "-")) == account)
    scope.append(
        func.coalesce(Run.config_snapshot["evidence_contract_version"].astext, "1")
        == str(snapshot.get("evidence_contract_version", 1))
    )
    return scope


def run_ids_match(column, run_ids):
    # One array bind avoids the driver's parameter ceiling as scan history grows.
    return column == any_(literal(run_ids, type_=ARRAY(PG_UUID(as_uuid=True))))


def current_review_evidence(cohort, readings, run_ids, *, name):
    """Select narrow winner keys; never copy financial reports through sorts."""
    if not run_ids:
        return select(cohort.c.id, cohort.c.order_reference).subquery()
    candidates = (
        select(cohort.c.id.label("cohort_id"), readings.c.id.label("finding_id"))
        .select_from(cohort)
        .join(readings, readings.c.order_reference == cohort.c.order_reference)
        .where(
            run_ids_match(readings.c.run_id, run_ids),
            readings.c.source_id != "",
            readings.c.source_id == cohort.c.source_id,
            readings.c.currency != "",
            readings.c.currency == cohort.c.currency,
            tuple_(readings.c.observed_at, readings.c.updated_at, readings.c.id)
            > tuple_(cohort.c.observed_at, cohort.c.updated_at, cohort.c.id),
        )
        .distinct(cohort.c.id)
        .order_by(cohort.c.id, readings.c.observed_at.desc(), readings.c.updated_at.desc(), readings.c.id.desc())
        .cte(f"{name}_candidates")
        .prefix_with("MATERIALIZED")
    )
    return (
        select(
            func.coalesce(candidates.c.finding_id, cohort.c.id).label("id"),
            cohort.c.order_reference,
        )
        .select_from(cohort.outerjoin(candidates, candidates.c.cohort_id == cohort.c.id))
        .subquery()
    )


async def period_evidence(db, tenant_id, run_id, *, root=None):
    """One authorized period's cohort with compatible later rechecks."""
    from app.models.transaction_ops import TransactionFinding, TransactionRun
    from app.schemas.transaction_runs import ReviewSpan
    from app.services.transaction_ops import state_service as state

    if root is None:
        root = await state.get_run(db, tenant_id, run_id)
    elif root.tenant_id != tenant_id or root.id != run_id:
        raise state.StateError("not_found", 404)
    if not root.params_json.get("review"):
        raise state.StateError("not_a_period_review", 422)
    span = ReviewSpan.model_validate(root.params_json["review"])
    from app.services.transaction_ops.daily_evidence import compatible_observation_runs

    f, r = TransactionFinding, TransactionRun
    cohort_scope = and_(
        r.config_id == root.config_id,
        or_(
            r.params_json["review"] == span.model_dump(mode="json"),
            and_(*compatible_observation_runs(root, span)),
        ),
    )
    replacement = replacement_scope(root.config_snapshot)
    replacement_filter = and_(*replacement) if replacement else literal(False)
    # JSON scope predicates badly underestimate run cardinality. Resolve the
    # immutable authorized run IDs first, so PostgreSQL can estimate findings
    # from ordinary indexed run_id values instead of multiplying nested scans.
    runs = (
        await db.execute(
            select(r.id, cohort_scope.label("cohort"), replacement_filter.label("replacement")).where(
                r.tenant_id == tenant_id, or_(cohort_scope, replacement_filter)
            )
        )
    ).all()
    cohort_ids = [row.id for row in runs if row.cohort]
    replacement_ids = [row.id for row in runs if row.replacement]
    name = f"review_{root.id.hex}"
    # Extract small identity/read-clock values once. Repeated JSONB lookups on
    # large, compressed evidence previously dominated both sorting and joins.
    facts = (
        func.jsonb_to_record(f.report_json)
        .table_valued(
            *(column(key, JSONB) for key in ("source", "targets", "_observation", "balance", "source_eligibility"))
        )
        .render_derived(name=f"{name}_facts", with_types=True)
        .lateral()
    )
    report = {key: facts.c[key] for key in ("source", "targets", "_observation", "balance", "source_eligibility")}
    reading_query = (
        select(
            f.id,
            f.run_id,
            f.order_reference,
            f.updated_at,
            evidence_time(report, f.updated_at).label("observed_at"),
            facts.c.source["record_id"].astext.label("source_id"),
            facts.c.balance["currency"].astext.label("currency"),
            facts.c.balance["status"].astext.label("balance_status"),
            eligible_reports(report).label("eligible"),
        )
        .select_from(f)
        .join(facts, true())
        .where(
            f.tenant_id == tenant_id,
            final_evidence(report),
        )
    )
    cohort_readings = (
        reading_query.where(run_ids_match(f.run_id, cohort_ids))
        .cte(f"{name}_cohort_readings")
        .prefix_with("MATERIALIZED")
    )
    # Rechecks may refresh the fixed cohort, never enlarge it. Do not decode
    # unrelated orders as history grows, or decode cohort findings twice.
    other_readings = reading_query.where(
        run_ids_match(f.run_id, sorted(set(replacement_ids) - set(cohort_ids))),
        f.order_reference.in_(select(cohort_readings.c.order_reference)),
    )
    readings = union_all(select(cohort_readings), other_readings).cte(f"{name}_readings").prefix_with("MATERIALIZED")
    cohort = (
        select(readings)
        .where(run_ids_match(readings.c.run_id, cohort_ids))
        .distinct(readings.c.order_reference)
        .order_by(
            readings.c.order_reference,
            readings.c.observed_at.desc(),
            readings.c.updated_at.desc(),
            readings.c.id.desc(),
        )
        .cte(f"{name}_cohort")
        .prefix_with("MATERIALIZED")
    )
    winners = current_review_evidence(cohort, readings, replacement_ids, name=name)
    latest = (
        select(f.id, f.run_id, winners.c.order_reference, f.report_json, f.updated_at, readings.c.balance_status)
        .join(winners, (f.id == winners.c.id) & (f.tenant_id == tenant_id))
        .join(readings, readings.c.id == winners.c.id)
        .where(readings.c.eligible)
        .subquery()
    )
    # Filter after winner selection: never resurrect a superseded exception.
    return latest, span


def result_category(latest):
    from sqlalchemy import case

    verdict = (
        latest.c.balance_status if "balance_status" in latest.c else latest.c.report_json["balance"]["status"].astext
    )
    return case(
        (verdict == "matched", "matched"),
        (
            verdict.in_(["difference", "mismatch", "missing_in_netsuite", "ambiguous", "currency_mismatch"]),
            "needs_review",
        ),
        else_="not_verified",
    )
